// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsio.proto

package org.newsio.grpc;

public final class Newsio {
  private Newsio() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface noParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.newsio.grpc.noParams)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.newsio.grpc.noParams}
   */
  public  static final class noParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.newsio.grpc.noParams)
      noParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use noParams.newBuilder() to construct.
    private noParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private noParams() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new noParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private noParams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_noParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_noParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.newsio.grpc.Newsio.noParams.class, org.newsio.grpc.Newsio.noParams.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.newsio.grpc.Newsio.noParams)) {
        return super.equals(obj);
      }
      org.newsio.grpc.Newsio.noParams other = (org.newsio.grpc.Newsio.noParams) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.newsio.grpc.Newsio.noParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.newsio.grpc.Newsio.noParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.noParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.newsio.grpc.Newsio.noParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.noParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.newsio.grpc.Newsio.noParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.noParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.newsio.grpc.Newsio.noParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.noParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.newsio.grpc.Newsio.noParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.noParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.newsio.grpc.Newsio.noParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.newsio.grpc.Newsio.noParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.newsio.grpc.noParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.newsio.grpc.noParams)
        org.newsio.grpc.Newsio.noParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_noParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_noParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.newsio.grpc.Newsio.noParams.class, org.newsio.grpc.Newsio.noParams.Builder.class);
      }

      // Construct using org.newsio.grpc.Newsio.noParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_noParams_descriptor;
      }

      @java.lang.Override
      public org.newsio.grpc.Newsio.noParams getDefaultInstanceForType() {
        return org.newsio.grpc.Newsio.noParams.getDefaultInstance();
      }

      @java.lang.Override
      public org.newsio.grpc.Newsio.noParams build() {
        org.newsio.grpc.Newsio.noParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.newsio.grpc.Newsio.noParams buildPartial() {
        org.newsio.grpc.Newsio.noParams result = new org.newsio.grpc.Newsio.noParams(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.newsio.grpc.Newsio.noParams) {
          return mergeFrom((org.newsio.grpc.Newsio.noParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.newsio.grpc.Newsio.noParams other) {
        if (other == org.newsio.grpc.Newsio.noParams.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.newsio.grpc.Newsio.noParams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.newsio.grpc.Newsio.noParams) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.newsio.grpc.noParams)
    }

    // @@protoc_insertion_point(class_scope:org.newsio.grpc.noParams)
    private static final org.newsio.grpc.Newsio.noParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.newsio.grpc.Newsio.noParams();
    }

    public static org.newsio.grpc.Newsio.noParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<noParams>
        PARSER = new com.google.protobuf.AbstractParser<noParams>() {
      @java.lang.Override
      public noParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new noParams(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<noParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<noParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.newsio.grpc.Newsio.noParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface listOfNewsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.newsio.grpc.listOfNews)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    java.util.List<org.newsio.grpc.Newsio.News> 
        getNewsListList();
    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    org.newsio.grpc.Newsio.News getNewsList(int index);
    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    int getNewsListCount();
    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    java.util.List<? extends org.newsio.grpc.Newsio.NewsOrBuilder> 
        getNewsListOrBuilderList();
    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    org.newsio.grpc.Newsio.NewsOrBuilder getNewsListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.newsio.grpc.listOfNews}
   */
  public  static final class listOfNews extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.newsio.grpc.listOfNews)
      listOfNewsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use listOfNews.newBuilder() to construct.
    private listOfNews(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private listOfNews() {
      newsList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new listOfNews();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private listOfNews(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                newsList_ = new java.util.ArrayList<org.newsio.grpc.Newsio.News>();
                mutable_bitField0_ |= 0x00000001;
              }
              newsList_.add(
                  input.readMessage(org.newsio.grpc.Newsio.News.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          newsList_ = java.util.Collections.unmodifiableList(newsList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_listOfNews_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_listOfNews_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.newsio.grpc.Newsio.listOfNews.class, org.newsio.grpc.Newsio.listOfNews.Builder.class);
    }

    public static final int NEWSLIST_FIELD_NUMBER = 1;
    private java.util.List<org.newsio.grpc.Newsio.News> newsList_;
    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    public java.util.List<org.newsio.grpc.Newsio.News> getNewsListList() {
      return newsList_;
    }
    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    public java.util.List<? extends org.newsio.grpc.Newsio.NewsOrBuilder> 
        getNewsListOrBuilderList() {
      return newsList_;
    }
    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    public int getNewsListCount() {
      return newsList_.size();
    }
    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    public org.newsio.grpc.Newsio.News getNewsList(int index) {
      return newsList_.get(index);
    }
    /**
     * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
     */
    public org.newsio.grpc.Newsio.NewsOrBuilder getNewsListOrBuilder(
        int index) {
      return newsList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < newsList_.size(); i++) {
        output.writeMessage(1, newsList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < newsList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, newsList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.newsio.grpc.Newsio.listOfNews)) {
        return super.equals(obj);
      }
      org.newsio.grpc.Newsio.listOfNews other = (org.newsio.grpc.Newsio.listOfNews) obj;

      if (!getNewsListList()
          .equals(other.getNewsListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNewsListCount() > 0) {
        hash = (37 * hash) + NEWSLIST_FIELD_NUMBER;
        hash = (53 * hash) + getNewsListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.newsio.grpc.Newsio.listOfNews parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.newsio.grpc.Newsio.listOfNews parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.newsio.grpc.Newsio.listOfNews prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.newsio.grpc.listOfNews}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.newsio.grpc.listOfNews)
        org.newsio.grpc.Newsio.listOfNewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_listOfNews_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_listOfNews_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.newsio.grpc.Newsio.listOfNews.class, org.newsio.grpc.Newsio.listOfNews.Builder.class);
      }

      // Construct using org.newsio.grpc.Newsio.listOfNews.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNewsListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (newsListBuilder_ == null) {
          newsList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          newsListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_listOfNews_descriptor;
      }

      @java.lang.Override
      public org.newsio.grpc.Newsio.listOfNews getDefaultInstanceForType() {
        return org.newsio.grpc.Newsio.listOfNews.getDefaultInstance();
      }

      @java.lang.Override
      public org.newsio.grpc.Newsio.listOfNews build() {
        org.newsio.grpc.Newsio.listOfNews result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.newsio.grpc.Newsio.listOfNews buildPartial() {
        org.newsio.grpc.Newsio.listOfNews result = new org.newsio.grpc.Newsio.listOfNews(this);
        int from_bitField0_ = bitField0_;
        if (newsListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            newsList_ = java.util.Collections.unmodifiableList(newsList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.newsList_ = newsList_;
        } else {
          result.newsList_ = newsListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.newsio.grpc.Newsio.listOfNews) {
          return mergeFrom((org.newsio.grpc.Newsio.listOfNews)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.newsio.grpc.Newsio.listOfNews other) {
        if (other == org.newsio.grpc.Newsio.listOfNews.getDefaultInstance()) return this;
        if (newsListBuilder_ == null) {
          if (!other.newsList_.isEmpty()) {
            if (newsList_.isEmpty()) {
              newsList_ = other.newsList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNewsListIsMutable();
              newsList_.addAll(other.newsList_);
            }
            onChanged();
          }
        } else {
          if (!other.newsList_.isEmpty()) {
            if (newsListBuilder_.isEmpty()) {
              newsListBuilder_.dispose();
              newsListBuilder_ = null;
              newsList_ = other.newsList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              newsListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNewsListFieldBuilder() : null;
            } else {
              newsListBuilder_.addAllMessages(other.newsList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.newsio.grpc.Newsio.listOfNews parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.newsio.grpc.Newsio.listOfNews) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.newsio.grpc.Newsio.News> newsList_ =
        java.util.Collections.emptyList();
      private void ensureNewsListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          newsList_ = new java.util.ArrayList<org.newsio.grpc.Newsio.News>(newsList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.newsio.grpc.Newsio.News, org.newsio.grpc.Newsio.News.Builder, org.newsio.grpc.Newsio.NewsOrBuilder> newsListBuilder_;

      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public java.util.List<org.newsio.grpc.Newsio.News> getNewsListList() {
        if (newsListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(newsList_);
        } else {
          return newsListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public int getNewsListCount() {
        if (newsListBuilder_ == null) {
          return newsList_.size();
        } else {
          return newsListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public org.newsio.grpc.Newsio.News getNewsList(int index) {
        if (newsListBuilder_ == null) {
          return newsList_.get(index);
        } else {
          return newsListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public Builder setNewsList(
          int index, org.newsio.grpc.Newsio.News value) {
        if (newsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsListIsMutable();
          newsList_.set(index, value);
          onChanged();
        } else {
          newsListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public Builder setNewsList(
          int index, org.newsio.grpc.Newsio.News.Builder builderForValue) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          newsList_.set(index, builderForValue.build());
          onChanged();
        } else {
          newsListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public Builder addNewsList(org.newsio.grpc.Newsio.News value) {
        if (newsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsListIsMutable();
          newsList_.add(value);
          onChanged();
        } else {
          newsListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public Builder addNewsList(
          int index, org.newsio.grpc.Newsio.News value) {
        if (newsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsListIsMutable();
          newsList_.add(index, value);
          onChanged();
        } else {
          newsListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public Builder addNewsList(
          org.newsio.grpc.Newsio.News.Builder builderForValue) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          newsList_.add(builderForValue.build());
          onChanged();
        } else {
          newsListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public Builder addNewsList(
          int index, org.newsio.grpc.Newsio.News.Builder builderForValue) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          newsList_.add(index, builderForValue.build());
          onChanged();
        } else {
          newsListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public Builder addAllNewsList(
          java.lang.Iterable<? extends org.newsio.grpc.Newsio.News> values) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, newsList_);
          onChanged();
        } else {
          newsListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public Builder clearNewsList() {
        if (newsListBuilder_ == null) {
          newsList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          newsListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public Builder removeNewsList(int index) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          newsList_.remove(index);
          onChanged();
        } else {
          newsListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public org.newsio.grpc.Newsio.News.Builder getNewsListBuilder(
          int index) {
        return getNewsListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public org.newsio.grpc.Newsio.NewsOrBuilder getNewsListOrBuilder(
          int index) {
        if (newsListBuilder_ == null) {
          return newsList_.get(index);  } else {
          return newsListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public java.util.List<? extends org.newsio.grpc.Newsio.NewsOrBuilder> 
           getNewsListOrBuilderList() {
        if (newsListBuilder_ != null) {
          return newsListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(newsList_);
        }
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public org.newsio.grpc.Newsio.News.Builder addNewsListBuilder() {
        return getNewsListFieldBuilder().addBuilder(
            org.newsio.grpc.Newsio.News.getDefaultInstance());
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public org.newsio.grpc.Newsio.News.Builder addNewsListBuilder(
          int index) {
        return getNewsListFieldBuilder().addBuilder(
            index, org.newsio.grpc.Newsio.News.getDefaultInstance());
      }
      /**
       * <code>repeated .org.newsio.grpc.News newsList = 1;</code>
       */
      public java.util.List<org.newsio.grpc.Newsio.News.Builder> 
           getNewsListBuilderList() {
        return getNewsListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.newsio.grpc.Newsio.News, org.newsio.grpc.Newsio.News.Builder, org.newsio.grpc.Newsio.NewsOrBuilder> 
          getNewsListFieldBuilder() {
        if (newsListBuilder_ == null) {
          newsListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.newsio.grpc.Newsio.News, org.newsio.grpc.Newsio.News.Builder, org.newsio.grpc.Newsio.NewsOrBuilder>(
                  newsList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          newsList_ = null;
        }
        return newsListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.newsio.grpc.listOfNews)
    }

    // @@protoc_insertion_point(class_scope:org.newsio.grpc.listOfNews)
    private static final org.newsio.grpc.Newsio.listOfNews DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.newsio.grpc.Newsio.listOfNews();
    }

    public static org.newsio.grpc.Newsio.listOfNews getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<listOfNews>
        PARSER = new com.google.protobuf.AbstractParser<listOfNews>() {
      @java.lang.Override
      public listOfNews parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new listOfNews(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<listOfNews> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<listOfNews> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.newsio.grpc.Newsio.listOfNews getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NewsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.newsio.grpc.News)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 _id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string author = 4;</code>
     * @return The author.
     */
    java.lang.String getAuthor();
    /**
     * <code>string author = 4;</code>
     * @return The bytes for author.
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>string date = 5;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 5;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>string imageLink = 6;</code>
     * @return The imageLink.
     */
    java.lang.String getImageLink();
    /**
     * <code>string imageLink = 6;</code>
     * @return The bytes for imageLink.
     */
    com.google.protobuf.ByteString
        getImageLinkBytes();
  }
  /**
   * Protobuf type {@code org.newsio.grpc.News}
   */
  public  static final class News extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.newsio.grpc.News)
      NewsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use News.newBuilder() to construct.
    private News(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private News() {
      title_ = "";
      description_ = "";
      author_ = "";
      date_ = "";
      imageLink_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new News();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private News(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              Id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              author_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              imageLink_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_News_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_News_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.newsio.grpc.Newsio.News.class, org.newsio.grpc.Newsio.News.Builder.class);
    }

    public static final int _ID_FIELD_NUMBER = 1;
    private int Id_;
    /**
     * <code>int32 _id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return Id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHOR_FIELD_NUMBER = 4;
    private volatile java.lang.Object author_;
    /**
     * <code>string author = 4;</code>
     * @return The author.
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <code>string author = 4;</code>
     * @return The bytes for author.
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 5;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 5;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGELINK_FIELD_NUMBER = 6;
    private volatile java.lang.Object imageLink_;
    /**
     * <code>string imageLink = 6;</code>
     * @return The imageLink.
     */
    public java.lang.String getImageLink() {
      java.lang.Object ref = imageLink_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageLink_ = s;
        return s;
      }
    }
    /**
     * <code>string imageLink = 6;</code>
     * @return The bytes for imageLink.
     */
    public com.google.protobuf.ByteString
        getImageLinkBytes() {
      java.lang.Object ref = imageLink_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (Id_ != 0) {
        output.writeInt32(1, Id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (!getAuthorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, author_);
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, date_);
      }
      if (!getImageLinkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, imageLink_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (Id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, Id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      if (!getAuthorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, author_);
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, date_);
      }
      if (!getImageLinkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, imageLink_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.newsio.grpc.Newsio.News)) {
        return super.equals(obj);
      }
      org.newsio.grpc.Newsio.News other = (org.newsio.grpc.Newsio.News) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getImageLink()
          .equals(other.getImageLink())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + _ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + IMAGELINK_FIELD_NUMBER;
      hash = (53 * hash) + getImageLink().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.newsio.grpc.Newsio.News parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.newsio.grpc.Newsio.News parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.News parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.newsio.grpc.Newsio.News parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.News parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.newsio.grpc.Newsio.News parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.News parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.newsio.grpc.Newsio.News parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.News parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.newsio.grpc.Newsio.News parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.newsio.grpc.Newsio.News parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.newsio.grpc.Newsio.News parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.newsio.grpc.Newsio.News prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.newsio.grpc.News}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.newsio.grpc.News)
        org.newsio.grpc.Newsio.NewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_News_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_News_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.newsio.grpc.Newsio.News.class, org.newsio.grpc.Newsio.News.Builder.class);
      }

      // Construct using org.newsio.grpc.Newsio.News.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        Id_ = 0;

        title_ = "";

        description_ = "";

        author_ = "";

        date_ = "";

        imageLink_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.newsio.grpc.Newsio.internal_static_org_newsio_grpc_News_descriptor;
      }

      @java.lang.Override
      public org.newsio.grpc.Newsio.News getDefaultInstanceForType() {
        return org.newsio.grpc.Newsio.News.getDefaultInstance();
      }

      @java.lang.Override
      public org.newsio.grpc.Newsio.News build() {
        org.newsio.grpc.Newsio.News result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.newsio.grpc.Newsio.News buildPartial() {
        org.newsio.grpc.Newsio.News result = new org.newsio.grpc.Newsio.News(this);
        result.Id_ = Id_;
        result.title_ = title_;
        result.description_ = description_;
        result.author_ = author_;
        result.date_ = date_;
        result.imageLink_ = imageLink_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.newsio.grpc.Newsio.News) {
          return mergeFrom((org.newsio.grpc.Newsio.News)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.newsio.grpc.Newsio.News other) {
        if (other == org.newsio.grpc.Newsio.News.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          onChanged();
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (!other.getImageLink().isEmpty()) {
          imageLink_ = other.imageLink_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.newsio.grpc.Newsio.News parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.newsio.grpc.Newsio.News) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int Id_ ;
      /**
       * <code>int32 _id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return Id_;
      }
      /**
       * <code>int32 _id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        Id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        Id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object author_ = "";
      /**
       * <code>string author = 4;</code>
       * @return The author.
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string author = 4;</code>
       * @return The bytes for author.
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string author = 4;</code>
       * @param value The author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string author = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthor() {
        
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>string author = 4;</code>
       * @param value The bytes for author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        author_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 5;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 5;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 5;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 5;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageLink_ = "";
      /**
       * <code>string imageLink = 6;</code>
       * @return The imageLink.
       */
      public java.lang.String getImageLink() {
        java.lang.Object ref = imageLink_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageLink_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imageLink = 6;</code>
       * @return The bytes for imageLink.
       */
      public com.google.protobuf.ByteString
          getImageLinkBytes() {
        java.lang.Object ref = imageLink_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageLink_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imageLink = 6;</code>
       * @param value The imageLink to set.
       * @return This builder for chaining.
       */
      public Builder setImageLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageLink_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imageLink = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageLink() {
        
        imageLink_ = getDefaultInstance().getImageLink();
        onChanged();
        return this;
      }
      /**
       * <code>string imageLink = 6;</code>
       * @param value The bytes for imageLink to set.
       * @return This builder for chaining.
       */
      public Builder setImageLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageLink_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.newsio.grpc.News)
    }

    // @@protoc_insertion_point(class_scope:org.newsio.grpc.News)
    private static final org.newsio.grpc.Newsio.News DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.newsio.grpc.Newsio.News();
    }

    public static org.newsio.grpc.Newsio.News getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<News>
        PARSER = new com.google.protobuf.AbstractParser<News>() {
      @java.lang.Override
      public News parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new News(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<News> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<News> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.newsio.grpc.Newsio.News getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_newsio_grpc_noParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_newsio_grpc_noParams_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_newsio_grpc_listOfNews_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_newsio_grpc_listOfNews_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_newsio_grpc_News_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_newsio_grpc_News_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014newsio.proto\022\017org.newsio.grpc\"\n\n\010noPar" +
      "ams\"5\n\nlistOfNews\022\'\n\010newsList\030\001 \003(\0132\025.or" +
      "g.newsio.grpc.News\"h\n\004News\022\013\n\003_id\030\001 \001(\005\022" +
      "\r\n\005title\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\016\n\006a" +
      "uthor\030\004 \001(\t\022\014\n\004date\030\005 \001(\t\022\021\n\timageLink\030\006" +
      " \001(\t2\254\001\n\013NewsService\022K\n\023fetchLatestTechN" +
      "ews\022\031.org.newsio.grpc.noParams\032\025.org.new" +
      "sio.grpc.News\"\0000\001\022P\n\030fetchLatestPolitica" +
      "lNews\022\031.org.newsio.grpc.noParams\032\025.org.n" +
      "ewsio.grpc.News\"\0000\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_newsio_grpc_noParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_newsio_grpc_noParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_newsio_grpc_noParams_descriptor,
        new java.lang.String[] { });
    internal_static_org_newsio_grpc_listOfNews_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_newsio_grpc_listOfNews_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_newsio_grpc_listOfNews_descriptor,
        new java.lang.String[] { "NewsList", });
    internal_static_org_newsio_grpc_News_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_newsio_grpc_News_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_newsio_grpc_News_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Author", "Date", "ImageLink", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
